### DISCUSSION TITLE
Kubernetes Secret and stringData

### DISCUSSION THREAD

**Discussion by bueti** [stefanprodan/timoni#394] [Q&A] [answered]
Hi there! New to Timoni and I really like what I'm seeing so far! 🙏 

I'm trying to figure out what's the best way to create a template for a Secret with stringData.

I have a Secret in Kubernetes which contains a configuration file. This file is mounted to the pod and read at startup. 
The secret looks something like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
  (...)
type: Opaque
stringData:
  configuration.yaml: |
    foo:
      host: some.host.example.com
      password: encrypted-with-helm-secrets-at-rest
``` 

The `corev1.#Secret.stringData` type seems to only accept `[string] string` ([ref](https://github.com/stefanprodan/timoni/blob/9efd697da787ac3412d31e61f77910d779a60aa3/examples/redis/cue.mod/gen/k8s.io/api/core/v1/types_go_gen.cue#L6780)). That would mean that the yaml inside the configuration file would just be a multi-line string in cue. 
Is there a better way to do this?

my current setup:

config.cue:
```cue
(...)
#Config: {
    	secret: [string]: string
}
```

secret.cue:
```cue
package templates

import (
	corev1 "k8s.io/api/core/v1"
)

#Secret: corev1.#Secret & {
	#config:    #Config
	apiVersion: "v1"
	kind:       "Secret"
	metadata:   #config.metadata
	type:       corev1.#SecretTypeOpaque
	stringData: #config.secret
}
```

values.cue:
```cue
values: {
﻿	secret: "configuration.yaml": """
		  foo:
		    host: some.host.example.com
		"""
}
