### DISCUSSION TITLE
How to generate multiple resources of same type?

### DISCUSSION THREAD

**Discussion by philipsd6** [stefanprodan/timoni#418] [Q&A] [answered]
I'm new to timoni and cuelang, but I'm excited about both! However, I'm struggling with how to implement a module where a container may be configured with multiple volumes. Typically, we see something like this:

```yaml
#Config: persistence: {
    enabled:      *true | bool
    storageClass: *"standard" | string
    size:         *"8Gi" | string
}
#Instance: {
    config: #Config
    objects: {
        pvc: #PersistentVolumeClaim & {#config: config}
    }
}
```

For my purposes I need to have two volumes: data and config. So I model it this way:

``` yaml
#Config: {
    persistence: [Name=_]: {
        enabled:      *false | bool
        mountPath:    *"/\(Name)" | string
        hostPath?:    string
        storageClass: *"standard" | string
        size:         *"1Gi" | string
    }
    persistence: config: {}
    persistence: data: {}
}
```
Then in my `values.yaml` I can enable either or both. And in my `templates/deployment.yaml` it's easy  enough to loop to create the `volumeMounts` and `volumes`:

``` yaml
volumeMounts: [
    for k, v in #config.persistence if v.enabled {
        {name: k, mountPath: v.mountPath}
    },
]
```

What I'm struggling with is how to loop to create the `#PersistentVolumeClaim` resources. If I loop over them like that in `#Instance`, I can adjust the pvc to get some additional data to merge in, i.e.:

``` yaml
for k, v in config.persistence if v.enabled {
    "\(k)": #PersistentVolumeClaim & {
        #config: config
        #name:   k
        #spec: {
            resources: requests: storage: v.size
            storageClassName: v.storageClass
            volumeName:       "\(config.metadata.name)-\(k)"
        }
    }
}
```

But I can't use that `#name` to merge in as `metadata.name` because I get a conflict:

`timoni.instance.objects.config.metadata.name: conflicting values "config" and "example-app":`

How do I do this? Since `metadata.name` is set by timoni with the build command I don't see how it's possible for it to generate two different PVs no matter what hoops I jump through in cuelang.

**Comment by philipsd6** [comment, marked as answer]
Never mind, I guess I solved my problem after finding #369 

Now I'm doing this and it works for me:

```yaml
#PersistentVolumeClaim: corev1.#PersistentVolumeClaim & {
    #config:    #Config
    #pvcName:   string
    #spec:      corev1.#PersistentVolumeClaimSpec
    apiVersion: "core/v1"
    kind:       "PersistentVolumeClaim"
    metadata: {name: #pvcName} & {
        for k, v in #config.metadata if k != "name" {
            "\(k)": v
        }
    }
```
