### DISCUSSION TITLE
Including external module dependencies in existing timoni module

### DISCUSSION THREAD

**Discussion by rrmistry** [stefanprodan/timoni#449] [Q&A] [answered]
## Business problem being solved for

> 🙏 My apologies in advance if I did not understand any timoni concepts correctly.

Currently, we have a large helm chart that includes external dependencies as sub-charts (e.g. a helm chart for databases, another for controllers, another for operators, etc.)

We are attempting to convert this helm chart into timoni module / bundle analogues.

The problem is: **How to reliably include external dependencies as part of a timoni module?**

Currently we use Helm [sub-charts](https://helm.sh/docs/helm/helm_dependency/#synopsis) to include external dependencies as part of our helm chart.

<details>

<summary>
Example <code>my-apps</code> Helm chart for reference
</summary>

```YAML
# my-apps/Charts.yaml
apiVersion: v2
name: my-apps
description: Helm Chart to deploy my app resources
type: application
version: 0.1.0
appVersion: 1.0.0

# Third party (external) dependencies
dependencies:

  - condition: redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: "20.0.3"

  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: "15.5.27"

---
# my-apps/templates/*.yaml

# ... classic helm chart template files for our app resources ...
...
# my-apps/templates/deployment.yaml
# my-apps/templates/ingress.yaml
# my-apps/templates/service.yaml
# my-apps/templates/secret.yaml
...

---
# my-apps/values.yaml

# ... my helm chart values ...
valueA: 123
valueB: def

# Third party (external) dependency's values
redis:
  enabled: true
  architecture: "standalone"
  auth:
    enabled: true
    username: default
    password: ********

postgresql:
  enabled: true
  architecture: "standalone"
  auth:
    enablePostgresUser: true
    postgresPassword: ********
    database: myapps
    username: myapps-user
    password: ********
```

</details>

The beauty of the helm chart approach is that we can reliably build or deploy our app and their dependencies as part of the same helm chart with single commands.

```sh
# Build
helm template --dependency-update --dry-run=server my-apps ./my-apps/

# Deploy
helm install my-apps ./my-apps/ -f ./my-apps/values.yaml -f overrides.yaml ...
```

## Known workarounds

With Timoni, as I understand it so far, the same end-result requires multiple steps:

- Build:

  1. Create your app's resources as part of a timoni module
      > 📝 Write CUE files ...
  1. Push your timoni module as an artifact to a container registry
      ```sh
      timoni mod push ...
      ```
  1. Create a timoni bundle that includes your module as part of this bundle
      > 📝 Write CUE files ...
  1. Include external dependencies as part of the same timoni bundle (e.g. `redis`, `postgres`, etc.)
      > 📝 Write CUE files ...
  1. Push this timoni bundle to a container registry
      ```sh
      timoni artifact push ...
      ```

- Deploy:

  1. Create a new timoni bundle that includes your combined timoni bundle from the build step (as a single timoni instance in this bundle)
      > 📝 Write CUE files ...
  1. Deploy timoni bundle to a Kubernetes cluster
      ```sh
      timoni bundle apply ...
      ```
      ✅ This will deploy your apps and their dependencies reliably as a single deployment

This observation was based on the end-to-end workflow described in the [timoni e2e.yaml workflow](https://github.com/stefanprodan/flux-aio/blob/1ada242d629349586fe1b99729dfa2afa00acb04/.github/workflows/e2e.yaml) file.

## Problem with workaround

This approach requires multiple steps to get to a clean singular timoni bundle that can achieve the same end-result (deploying our app and its dependencies reliably and together).

## Best solution (so far)

The cleanest solution I could find so far was to use [Flux's CRDs](https://fluxcd.io/flux/components/helm/helmreleases/) and deploy multiple custom resources for `HelmRepository` and `HelmRelease` type that would include the external dependencies as part our module.

But this approach itself has a dependency on having Flux installed on the cluster beforehand.

## Conclusion

It is still ideal to have timoni allow including an external bundle within a module as an external dependency (not requiring the cluster to have Flux already installed).

But I'm not sure if this is a valid feature request or if this is possible but I don't know how to do it yet.
