### ISSUE TITLE
Version value is not passed to @tag

### ISSUE THREAD

**Issue by Sprootsy** [stefanprodan/timoni#159]
I modified the default timoni.cue file to see if I could add an annotation based on the value given to `--version` flag.
```
// The instance name and namespace tag values
// are injected at runtime by Timoni.
config: metadata: {
	name:      string @tag(name)
	namespace: string @tag(namespace)
	labels: test: string @tag(version)
}
```
However this seems to be ignored.

While using a fixed string:
```
config: metadata: {
	name:      string @tag(name)
	namespace: string @tag(namespace)
	labels: test: "some text"
}
```
results in:
```
metadata:
  labels:
    app.kubernetes.io/name: test
    test: some text
  name: test-cd2239b7
  namespace: default
```

I think it would be useful to pass the value of the version flag to cue
