### ISSUE TITLE
The Bundle API should allow to read data from K8s configMaps and secrets

### ISSUE THREAD

**Issue by denist-huma** [stefanprodan/timoni#167]
My K8s operator knows how to create a redis instance and put a redis URL to a secret. I can supply a hostname, but the password is generated. How can I get a password from the secret? Same for CM.
For K8s apps I would use valueFrom.secretKeyRef:

```yaml
      env:
        - name: redisURL
          valueFrom:
            secretKeyRef:
              key: password
              name: redis-secret
```

For example I have a bundle:

```cue
bundle: {
	apiVersion: "v1alpha1"
	name:       "podinfo"
	instances: {
		redis: {
			module: {
				url:     "oci://ghcr.io/compose-operator-examples/modules/redisclaim"
				version: "0.1.1"
				values:
					managedConnectionSecretRef: {
						name: "redis-secret"
					}
			}
			namespace: "podinfo"
		}
		podinfo: {
		    module: url:     "oci://ghcr.io/stefanprodan/modules/podinfo"
		    module: version: "6.3.5"
		    namespace: "podinfo"
		    values: caching: {
		        enabled:  true
		        redisURL: "tcp://redis-redis:6379"
		    }
		}
	}
}
```
