### ISSUE TITLE
Error vendoring rook crds

### ISSUE THREAD

**Issue by Pythoner6** [stefanprodan/timoni#277]
I ran into this error 
```
9:47PM ERR could not convert schema for version v1alpha1 to CUE: constraint not allowed because type array is excluded
```
while trying to run `timoni mod vendor crd -f ...` for the rook crds (https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/templates/resources.yaml). Specifically it seems to be the ObjectBucket crd causing problems:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: objectbuckets.objectbucket.io
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: objectbucket.io
  names:
    kind: ObjectBucket
    listKind: ObjectBucketList
    plural: objectbuckets
    singular: objectbucket
    shortNames:
      - ob
      - obs
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                storageClassName:
                  type: string
                endpoint:
                  type: object
                  nullable: true
                  properties:
                    bucketHost:
                      type: string
                    bucketPort:
                      type: integer
                      format: int32
                    bucketName:
                      type: string
                    region:
                      type: string
                    subRegion:
                      type: string
                    additionalConfig:
                      type: object
                      nullable: true
                      x-kubernetes-preserve-unknown-fields: true
                authentication:
                  type: object
                  nullable: true
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                additionalState:
                  type: object
                  nullable: true
                  x-kubernetes-preserve-unknown-fields: true
                reclaimPolicy:
                  type: string
                claimRef:
                  type: object
                  nullable: true
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
```

Unfortunately I'm not super well versed in k8s crd definitions, and the error message is very obtuse (I had to manually check which resource it even was because all it gave me was the version), so I'm really not sure what's going on here.
