### ISSUE TITLE
Wrong cue type: {} when generating vendor crd

### ISSUE THREAD

**Issue by Aoao54** [stefanprodan/timoni#278]
Hi team,
When generating vendor of crd.yaml resources with the x-kubernetes-preserve-unknown-fields like below:

```
spec:
  description: Specification of the desired behavior of the pod.
  type: object
  x-kubernetes-preserve-unknown-fields: true
```
the output is 
```
// Specification of the desired behavior of the pod.
spec?: {}
```
But in the current version of cue, the {} means the empty struct instead of {...}  arbitrary struct. 
So the correct output value is 
```
// Specification of the desired behavior of the pod.
spec?: {...}
```
Then you can add anything you want of it.
cc @yujunz
