### ISSUE TITLE
ERR PersistentVolumeClaim/storage not found: the server could not find the requested resource

### ISSUE THREAD

**Issue by jmgilman** [stefanprodan/timoni#305]
When attempting to apply a Deployment object that depends on a PVC, the `timoni apply` command fails with:

```
ERR PersistentVolumeClaim/my-pvc not found: the server could not find the requested resource
```

Example YAML:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/version: 0.0.0-devel
    name: myapp
  name: myapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
        - image: myimage:tag
          imagePullPolicy: IfNotPresent
          name: app
          volumeMounts:
            - mountPath: /storage
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: class
---
```

When applying the manifests directly to the cluster using `kubectl apply -f` the same issue is _not_ observed and the deployment waits for the PVC to be created before starting.
